import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Raleway } from 'next/font/google';
import  Navbar  from "./components/Navbar/Navbar";
import { Suspense } from "react";
import MusicPlayer from "./components/MusicPlayer/TestPlayer";
import { MusicPlayerProvider } from "./context/NewContext";

import NewNavbar from "./components/Navbar/NewNavbar";
const raleway = Raleway({ subsets: ['latin'], weight: ['400', '700'] });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${raleway.className} antialiased`}
      >
            <NewNavbar />
        <MusicPlayerProvider>
          <div className=" relative mt-10 w-full h-full" >
            <Suspense fallback={<div>Loading...</div>}>
                {children}
            </Suspense>
            <MusicPlayer />
          </div>
            
        </MusicPlayerProvider>
       
      </body>
    </html>
  );
}
